# Usage: FROM [image name]
FROM ubuntu:22.04

MAINTAINER Adithya Khamithkar <nkadithya31@gmail.com>

# Initialize
RUN apt-get update && apt-get install -y net-tools vim

# Install nginx
#RUN apt-get install -y nginx

# Open ports
EXPOSE 80

# Start nginx
